from typing import TextIO

def main():
    # Recharger les mots et descriptions après réinitialisation de l'état

    mots = [
        "dessiner","écrire","compter","lire","faire de la logique","réfléchir","penser",
        "regarder","jouer au puzzle","alphabet","orientation","mathématique","chiffres",
        "puzzle","lego","circuit à bille","labyrinthe","mots-mélés","puissance 4",
        "bataille navale","fantome","princesse et chevalier","contraire","reproduction","uno",
        "parler","décrire","faire du sport","découper","qui est-ce?","échecs","MasterMind",
        "mémoire","memory",
        "télescope","astronomie","manger","brosser les dents","pot","bobo","laver les mains",
        "dormir","douche","bain","manger","dessins animés","jouer au train","jouer à cache-cache",
        "son","syllabes","ventilateur","nager","école"
    ]

    descriptions = {
        "dessiner" : "a hand holding a pencil, sketching on a blank sheet of paper with visible lines forming a simple drawing",
        "écrire" : "a hand writing cursive text in a notebook with a fountain pen or pencil, visible letters forming words",
        "compter" : "a child or person pointing at or arranging colorful counting beads or using their fingers to count",
        "lire" : "a person sitting with an open book, eyes focused on the text, surrounded by a quiet, studious atmosphere",
        "faire de la logique" : "a person solving a logic grid or connecting shapes with lines, with a thoughtful expression",
        "réfléchir" : "a person resting their chin on their hand, looking slightly upward, with abstract symbols or question marks around",
        "penser" : "a silhouette or bust with a glowing brain, lightbulbs or gears emerging in a symbolic ""thinking"" aura",
        "regarder" : "a person peering closely at something with attention, possibly holding a magnifying glass or looking through glasses",
        "jouer au puzzle" : "a person assembling a jigsaw puzzle on a table, focused, with several scattered pieces around",
        "alphabet" : "a spread of handwritten or drawn alphabet letters (A to Z), stylized, possibly floating or arranged in rows",
        "orientation" : "a person studying a map or using a compass, possibly turning the paper, with signs or arrows in the scene",
        "mathématique" : "a blackboard or paper filled with mathematical symbols, numbers, and equations, with a hand writing them",
        "chiffres" : "large stylized numbers (0–9), handwritten or painted, floating or scattered, in different sizes and orientations",
        "puzzle" : "scattered jigsaw puzzle pieces on a table, some connected to form part of an image, others spread around randomly",
        "lego" : "colorful interlocking LEGO bricks partially assembled into a small structure or building, with extra pieces nearby",
        "circuit à bille" : "a marble run track with slopes, spirals, and tunnels, and a few marbles poised to roll down",
        "labyrinthe" : "a flat, hand-drawn maze with thick walls and a visible start and end point, possibly with a small figure inside",
        "mots-mélés" : "a square grid filled with random letters, with some words circled or highlighted diagonally and horizontally",
        "puissance 4" : "a vertical grid game with red and yellow discs, some placed in the slots, others ready to be played",
        "bataille navale" : "a paper or board with two grids, some with small ship icons, and pegs marking hits and misses",
        "fantôme" : "a classic ghost shape — white, floating, with round black eyes and a wavy lower edge, slightly translucent",
        "princesse et chevalier" : "two figurines or costumes — one of a princess in a gown and tiara, and one of a knight in armor with a toy sword",
        "contraire" : "two simple images side by side showing opposites (e.g., big and small animals, day and night, hot and cold)",
        "reproduction" : "a person copying a shape or drawing from one paper to another, side-by-side comparison of original and replica",
        "uno" : "a fan of colorful UNO cards in a player’s hand, with the pile and discard stack on a table",
        "parler" : "a person mid-conversation, mouth open slightly, with subtle speech lines or sound waves coming from the mouth",
        "décrire" : "a person pointing at an object while speaking, with a thoughtful expression and gestures suggesting explanation",
        "faire du sport" : "a person actively running, jumping, or lifting a dumbbell, showing motion and dynamic posture",
        "découper" : "a hand holding scissors cutting through a sheet of colored paper, with visible cut-out shapes around",
        "qui est-ce?" : "a tabletop game with a grid of small character faces, some flipped down, and a player peeking over it",
        "échecs" : "a chessboard mid-game with classic black and white pieces, some captured pieces lying beside the board",
        "MasterMind" : "a game board with rows of colored pegs and small black and white indicator pins, in mid-play",
        "mémoire" : "a symbolic brain illustration with glowing areas or lightbulbs, surrounded by icons like books, clocks, and puzzle pieces, evoking the concept of remembering",
        "memory" : "several square cards laid face down or turned over in pairs, showing simple matching illustrations or icons, arranged in a neat grid on a table",
        "télescope" : "a standing telescope on a tripod pointed at the sky, with a person peering through it under a starry night",
        "astronomie" : "a star chart, planets, and constellations in the sky, with a person looking up in awe or studying space diagrams",
        "manger" : "a person sitting at a table with a plate of food, holding a fork or spoon near their mouth, mid-bite",
        "brosser les dents" : "a child brushing their teeth in front of a mirror, foam around their mouth, holding a toothbrush",
        "pot" : "a small colorful potty on floor, with a toddler sitting on it, looking relaxed",
        "bobo" : " child with a small bandage on their knee or elbow, a tear on their cheek, and a comforting adult nearby",
        "laver les mains" : "hands with soap under the water splashing into a sink",
        "dormir" : "a person peacefully in bed under a blanket, eyes closed, with a calm expression and ""Zzz"" symbols nearby",
        "douche" : "a showerhead and shower tray with water flowing, steam rising, and droplets splashing around",
        "bain" : "a bathtub filled with bubbles, rubber duck nearby, with relaxed body language",
        "manger" : "a person lifting a spoon or fork to their mouth, with a plate of food in front, mid-bite",
        "dessins animés" : "a glowing screen, colorful characters visible on the screen",
        "jouer au train" : "a small toy train on tracks, with small characters and train station",
        "jouer à cache-cache" : "a child hiding behind furniture or a curtain, peeking out with a playful smile",
        "son" : "an abstract representation of a mouth next to separated syllables written clearly, with speech waveforms or pronunciation marks",
        "syllabes" : "a large word broken down into colored blocks or sections, each block showing a different syllable (e.g., “ma”, “ri”, “ne”), arranged visually",
        "ventilateur" : "a standing or tabletop fan with spinning blades, slightly tilted, with motion lines or wind waves suggesting airflow",
        "abeille" : " A realistic bee with fuzzy yellow and black stripes hovering over a flower, with fine detail on the wings and legs",
        "abricot" : " a soft orange apricot with velvety skin, shown whole and halved to reveal the pit",
        "ampoule" : " A classic incandescent light bulb with a glowing filament, shown in a sketchy style with reflections on the glass",
        "ananas1" : " a whole pineapple with a spiky crown and textured yellow-brown skin, standing upright",
        "ananas2" : " A spiky, textured pineapple with a leafy crown, resting on a surface with detailed cross-hatching",
        "araignée" : " A spider with a round body and long legs, drawn in a web, depicted with fine ink lines",
        "arbre" : " A tall tree with a thick trunk and detailed leaves, showing bark texture and branching limbs",
        "armoire" : " A wooden wardrobe with detailed grain texture and two doors slightly open, revealing shelves inside",
        "ascenseur" : " An elevator with open sliding doors, showing the interior with panel buttons and lighting",
        "avion" : " A commercial airplane flying across a lightly clouded sky, with detailed engines and wings",
        "baba" : " a small rum-soaked cake on a plate with syrup dripping",
        "bague" : " a close-up of a decorative ring with a gemstone on a velvet cushion",
        "balade" : " a person strolling through a peaceful countryside path with trees and birds",
        "balançoire" : " A wooden swing hanging from ropes tied to a tree branch, gently tilted as if just used",
        "balle" : " A round ball, slightly shadowed beneath, with texture suggesting rubber or plastic material",
        "ballon" : " A helium balloon floating with a string, slightly crinkled, reflecting light on its surface",
        "banane1" : " a ripe yellow banana, slightly curved, with one end peeled open showing the fruit inside",
        "banane2" : " A ripe banana, slightly curved, with dark speckles on its peel and realistic stem details",
        "bateau1" : " a small boat with a sail or motor, floating on calm water or docked at a pier",
        "bateau2" : " A sailboat on calm water, with sails filled by wind and ripples on the surface",
        "bazar" : " a crowded market with fabrics, spices, and goods displayed chaotically",
        "bebe" : " A baby crawling on a blanket, with round cheeks and soft features, in a delicate sketch style",
        "bébé" : " a baby sitting on a blanket, wearing a onesie, with a pacifier or rattle nearby",
        "biberon" : " A baby bottle with a rubber nipple and measuring lines, half-filled with milk, placed on a surface",
        "bille" : " A group of glass marbles with swirling colors and reflections, arranged randomly",
        "biscuit" : " A round cookie with visible grains and a slightly cracked surface, surrounded by crumbs",
        "boite" : " A square box slightly open, revealing contents inside, with taped edges and shadowed folds",
        "bol" : " A ceramic bowl with a rounded lip, seen from a three-quarter angle, with shadowing under it",
        "bonet" : " A wool knit cap with a pompom, folded at the rim and softly textured",
        "bouche" : " A softly drawn mouth with slightly open lips, showing a subtle smile",
        "brosse" : " A hand brush with bristles and a curved handle, laying flat and partially shaded",
        "bulldozer" : " A heavy construction bulldozer with thick tracks and a large front blade, detailed with mud",
        "cabane" : " a small wooden hut in a plain",
        "cacao" : " a branch with cocoa pods and open pod revealing cacao beans",
        "cadeau" : " A wrapped gift box with ribbon and bow, drawn with folded paper edges and shadows",
        "café" : " a steaming cup of coffee on a saucer, with a small spoon and sugar cube",
        "camion" : " A delivery truck with a box trailer, shown in profile with clear wheels and cabin details",
        "canapé" : " a soft cushioned sofa with a folded blanket and pillow",
        "canard" : " A duck floating on water, with a rounded body, beak, and feathers rendered in fine ink lines",
        "cape" : " a flowing superhero cape attached at the shoulders, fluttering behind a standing figure",
        "capitaine" : " A sea captain in a uniform with a hat, holding a telescope and standing confidently",
        "caporal" : " a uniformed corporal saluting with a military badge visible",
        "carafe" : " a glass carafe half-filled with water, sitting on a wooden table",
        "carotte1" : " a fresh orange carrot with leafy green tops, lying on a wooden table or in soil",
        "carotte2" : " A carrot with leafy greens, drawn with textured ridges and slight imperfections in the root",
        "cascade" : " a waterfall flowing between rocks into a stream, surrounded by greenery",
        "casque" : " A protective helmet with straps, drawn from a top-side angle with internal padding details",
        "caveau" : " a stone burial vault door partly open, with steps descending into darkness",
        "caverne" : " A dark rocky cave entrance surrounded by jagged stones and shadows inside",
        "cerise" : " A pair of red cherries connected by a stem with a leaf, showing glossy surface and dimples",
        "chaise" : " A wooden chair with a high backrest and visible wood grain, slightly tilted for perspective",
        "chapeau" : " a wide-brimmed hat with a ribbon around the base, resting on a hook or worn on a head",
        "chat" : " A domestic cat sitting calmly, with detailed fur, whiskers, and curled tail",
        "chien" : " A friendly dog sitting upright, tongue out, with floppy ears and visible fur texture",
        "ciseaux" : " A pair of scissors open halfway, with sharp blades and molded plastic handles",
        "clé" : " a metallic key with a round head and jagged edge, resting on a flat surface or hanging from a ring",
        "coccinelle" : " a red ladybug with black spots, crawling on a green leaf or flying with open wings",
        "cochon" : " A plump pig with a curly tail, standing in profile with light shading on its body",
        "coq" : " A rooster with detailed feathers, a comb on its head, and a proud stance",
        "coquillage" : " a spiral seashell with ridged texture, lying in the sand near the seashore",
        "couette" : " A folded duvet with visible stitching lines and puffy texture",
        "coussin" : " A soft, square or round fabric pillow with stitching, sometimes patterned, resting on a sofa or bed",
        "couteau" : " A kitchen knife with a reflective blade and a wooden handle, resting flat",
        "crocodile1" : " a green crocodile with rough scales, long snout, and sharp teeth, lying partially in water",
        "crocodile2" : " A crocodile lying near a riverbank, with rough scales, sharp teeth, and textured claws",
        "dada" : " a small child's rocking horse with playful carvings",
        "dague" : " a sharp medieval dagger with ornate handle and sheath",
        "data" : " a stylized drawing of binary code and data nodes linked together",
        "dessert" : " A fancy dessert in a bowl, like a layered parfait or mousse with toppings",
        "dinosaure" : " A standing dinosaur like a T-Rex, roaring, with scaly skin and clawed limbs",
        "dodo" : " a chubby extinct dodo bird standing on a tropical beach",
        "dragon" : " A mythical dragon flying with wings spread, breathing fire, covered in detailed scales",
        "école" : " A small school building with windows, a bell tower, and children playing outside",
        "éléphant" : " a large gray elephant with long trunk and tusks, standing in a savannah or near trees",
        "étoile" : " A single bright star shining in a dark sky, with subtle rays and tiny surrounding stars",
        "façade" : " the front of a decorative building with windows and moldings",
        "fagot" : " a tied bundle of firewood resting on grass",
        "falot" : " an old-fashioned lantern with a candle glowing inside",
        "famille" : " A group of people of varying ages, including adults and children, standing or sitting close together, showing warmth and connection",
        "fenêtre" : " A window with open shutters, showing light pouring in and curtain folds",
        "fenouille" : " A bulbous vegetable with pale green layers, feathery fronds, and a slightly sweet aroma, often shown sliced or whole",
        "fille" : " A young girl standing with a playful pose, wearing a dress and holding a toy",
        "fusée" : " a rocket launching into the sky, with flames and smoke at its base, heading into space",
        "gala" : " elegantly dressed people entering a theater with red carpet",
        "galette1" : " a rustic round cake with a golden crust on a baking tray",
        "galette2" : " A round pastry with a textured top crust and a flaky edge, slightly cracked open",
        "garage1" : " a car inside a mechanic's garage, tools hanging on the wall",
        "garage2" : " A garage with an open door showing a parked car and tools on the walls",
        "garçon" : " A young boy smiling and running, wearing shorts and sneakers",
        "gateau" : " A frosted cake on a plate, with visible layers, icing details, and candles",
        "gaufre" : " a waffle on a plate with melted chocolate and strawberries",
        "glace1" : " an ice cream cone with scoops of different flavors, slightly melting, held in a hand",
        "glace2" : " An ice cream cone with two scoops melting slightly, drawn with dripping detail",
        "gourde" : " A reusable water bottle with a screw cap, standing upright with a logo or sticker",
        "grotte" : " An enclosed cave interior with stalactites and stalagmites, dimly lit from the entrance",
        "guitare" : " An acoustic guitar resting against a chair, strings and wood grain clearly drawn",
        "hélicoptère" : " A helicopter hovering above the ground with spinning rotor blades and landing skids",
        "imprimante" : " A printer ejecting a printed sheet, with visible tray and button panel",
        "jade" : " a polished green jade stone displayed in a small box",
        "jupe1" : " a flared skirt with pleats, displayed on a mannequin or folded on a shelf",
        "jupe2" : " A pleated skirt hanging on a hanger, showing fabric folds and waistline",
        "kaki" : " a kaki fruit cut in half showing its texture",
        "karaté" : " a martial artist in mid-kick pose wearing a gi",
        "kayak" : " a person paddling a kayak down a river with splashes",
        "képi" : " a flat-topped military-style hat with a short visor, neatly placed on a uniform or table",
        "lampe" : " A desk lamp with an adjustable arm casting light on a book below",
        "lapin1" : " a fluffy bunny with long ears and twitching nose, sitting on grass",
        "lapin2" : " A rabbit sitting on its hind legs with long ears and soft fur texture",
        "lasso" : " a cowboy swinging a rope above his head in the desert",
        "lavabo" : " a ceramic sink with a faucet and a towel hanging nearby",
        "laveuse" : " an old-style washing machine with clothes spilling out",
        "lit" : " A made bed with a blanket, pillow, and headboard in a calm setting",
        "livre" : " An open book with visible lines of text and slightly curled pages",
        "local" : " a small neighborhood shop with striped awning and open door",
        "lune" : " a glowing crescent moon in a starry night sky, with visible craters and a soft halo around it",
        "lunette1" : " a pair of eyeglasses with round or rectangular lenses, folded or worn on a face",
        "lunette2" : " A pair of eyeglasses with round lenses and thin frame, resting on a surface",
        "magasin" : " A small shop front with a sign and display window filled with goods",
        "maison" : " A cozy house with a pitched roof, chimney, and a garden in front",
        "manteau" : " A winter coat with buttons and pockets hanging from a coat hook",
        "mare" : " a small pond with lily pads and reeds, surrounded by grass and small stones",
        "marteau" : " A hammer with a wooden handle and metal head, lying beside nails",
        "médicaments" : " A group of small items like pill bottles, blister packs, or loose capsules and tablets, arranged neatly on a surface",
        "métro" : " a subway train emerging from a tunnel, with sliding doors and passengers inside or waiting",
        "micro" : " a handheld microphone with a mesh head, connected to a cable, ready for speech or singing",
        "mine" : " An entrance to a mine carved into a rocky hill, with tracks and tools nearby",
        "minuteur" : " A kitchen timer with a round dial and pointer, slightly tilted",
        "montagne" : " A mountain range with snow-capped peaks and mist around the base",
        "montre" : " A wristwatch with visible time hands and leather strap, displayed flat",
        "mouche" : " A common housefly with transparent wings and fine hairs on its body",
        "moustique" : " A mosquito with thin legs and long proboscis, hovering midair",
        "nager" : " A person moving through water using coordinated arm and leg strokes, creating ripples and splashes, often seen in a pool or natural body of water",
        "nappe" : " a table covered by a patterned cloth with plates set",
        "navet" : " A round root vegetable with a purple top and white bottom, slightly rough skin, shown whole or sliced on a rustic table",
        "ordinateur" : " A laptop open on a desk, showing a glowing screen and keyboard",
        "ours" : " A bear standing on hind legs with fur detail and strong paws",
        "paille" : " A drinking straw, either sticking out of a glass",
        "panier" : " A woven basket with handles, filled with fruits or cloth",
        "pansements" : " A few adhesive bandages in different sizes, unwrapped and laying flat",
        "pantalon1" : " a pair of neatly folded pants or trousers, with visible waistband and pockets",
        "pantalon2" : " A pair of trousers folded neatly, showing pockets and stitching",
        "papa" : " a father lifting his child playfully in the air",
        "papillon" : " a colorful butterfly with open wings, showing symmetrical patterns, resting on a flower",
        "parapluie" : " An open umbrella with curved handle, water droplets on its fabric",
        "pelleteuse" : " A large yellow construction machine with a rotating cab and a long articulated arm ending in a metal bucket, digging into the ground on a construction site",
        "pétrin" : " A large bowl with dough being mixed, flour spread on the surface",
        "photographie" : " A vintage camera on a tripod taking a picture of a subject",
        "piquet" : " A wooden stake hammered into the ground with a rope tied around it",
        "piscine" : " A swimming pool with water ripples and a ladder at the side",
        "plage" : " A beach with sand, seashells, and waves gently washing ashore",
        "poisson" : " A fish swimming in water with scales and fins visible",
        "pomme" : " A round fruit with smooth skin, typically red, green, or yellow, with a small stem on top and a slight shine, resting on a textured surface",
        "popote" : " a bubbling pot on a stove with steam rising",
        "poule" : " A plump farm bird with feathers, a small red comb on its head, and a beak, often pecking at the ground or sitting in straw",
        "puzzle" : " A set of interlocking cardboard pieces, some assembled to form part of an image, laid out on a table with scattered loose pieces",
        "radiateur" : " A metal heating unit with vertical or horizontal panels, often mounted on a wall, with visible pipes and temperature control knob",
        "rame" : " a long oar with a wide blade, resting beside a boat or being held by a rower",
        "rat" : " A small gray rodent with a pointed snout, long whiskers, rounded ears, and a thin, hairless tail, often seen sniffing or scurrying near walls or corners",
        "robot" : " A humanoid robot with joints, antennas, and a glowing eye",
        "roue" : " A spoked wheel lying on its side, with metal and rubber textures",
        "rubis" : " A deep red, faceted gemstone with a glossy surface, often shown set in a ring or lying on a velvet cloth under soft lighting",
        "ruche" : " a beehive hanging from a tree branch or in a wooden box, with bees flying nearby",
        "sac" : " A backpack with zippers and padded straps, slightly opened at the top",
        "sacoche" : " A compact shoulder bag or satchel with a flap or zipper, often made of leather or fabric, used to carry small personal items",
        "salade" : " a bowl of green leafy salad with slices of vegetables like cucumber and tomato inside",
        "sandale" : " An open-toe shoe with straps over the foot and around the ankle, often with a flat sole, exposing most of the foot",
        "satellite" : " An orbital satellite with solar panels extended, floating in space",
        "savate1" : " a worn boxing shoe with frayed laces and dust",
        "savate2" : " A casual slipper with worn fabric and soft sole texture",
        "scie" : " A handsaw with a toothed blade and wooden handle, resting on wood shavings",
        "serpent" : " A coiled snake with scales and a forked tongue extended",
        "short" : " A pair of athletic shorts folded, with elastic waistband and side stripe",
        "singe" : " A monkey hanging by its tail from a branch, reaching for a banana",
        "soleil1" : " a bright yellow sun with rays extending outward, shining in a clear blue sky",
        "soleil2" : " A bright sun with radiating lines and soft glow, partially behind clouds",
        "souris" : " A small mouse peeking from behind a corner with a long tail",
        "spatule" : " A cooking spatula with a flat head and ergonomic handle, lying on a counter",
        "sucre" : " Sugar cubes stacked with granules around, lightly sketched for texture",
        "table" : " A wooden table with visible grain, seen in three-quarter perspective",
        "tableau" : " A classroom chalkboard with chalk dust, framed by wood",
        "tablette" : " A thin rectangular digital device with a touch screen, shown flat or held in hands, often displaying colorful icons or apps",
        "tabouret" : " A small stool with three legs, seen from above with shadow on the floor",
        "tasse" : " A ceramic mug, held by a rounded handle",
        "taxi1" : " a classic yellow taxi car with a roof sign, parked at a curb or picking up passengers",
        "taxi2" : " A yellow taxi car with a sign on top, seen from the side in the street",
        "téléphone" : " A classic handset telephone with coiled wire, resting on a desk",
        "téléviseur" : " A flat-screen TV on a stand, turned on with visible glow",
        "tirelire" : " a piggy bank in the shape of a pig, with a coin slot on its back and coins nearby",
        "tirroir" : " An open drawer with visible contents like papers and tools",
        "tobogan" : " a colorful playground slide with stairs, curving downward, and a child ready to slide",
        "toge" : " a roman-style toga worn by a figure in sandals",
        "toilettes" : " A small restroom with a toilet and sink, shown in clean lines",
        "toit" : " The slanted or flat upper structure of a building, made of tiles, shingles, or metal, often shown with chimneys or eaves",
        "tomate" : " a plump red tomato with a green stem, freshly picked and slightly shiny",
        "tortue" : " A turtle walking slowly with a dome-shaped shell and wrinkled limbs",
        "tracteur1" : " a red or green farm tractor with large wheels, parked in a field or driving through soil",
        "tracteur2" : " A farm tractor with large wheels, drawn from the front at an angle",
        "train" : " A passenger train on rails, shown from the side with windows",
        "trépied" : " A camera tripod with extended legs and mounted camera on top",
        "trotinette" : " A two-wheeled ride-on toy or vehicle with a narrow footboard, handlebars for steering, and often a rear brake, used by a child pushing off the ground with one foot",
        "truelle1" : " a metal trowel with a wooden handle, covered in cement or used beside bricks",
        "truelle2" : " A masonry trowel with a metal blade and wooden handle, lying on bricks",
        "tube" : " A cylindrical container or hollow object, such as a toothpaste tube or a wide plastic pipe segment, shown in use or lying flat",
        "tutu" : " a fluffy ballerina tutu skirt with layers of tulle, resting on a hanger or worn by a child",
        "valise" : " a travel suitcase with handles and wheels, slightly open with clothes spilling out",
        "vase" : " a delicate porcelain vase with a few wilted flowers",
        "vélo" : " A bicycle with two wheels, pedals, and a basket in front",
        "ventilateur" : " A standing fan with spinning blades, air lines drawn to show motion",
        "verre" : " A transparent drinking glass, empty or filled with liquid, reflecting light and casting soft shadows on the surface",
        "veste" : " A long-sleeved garment with buttons or a zipper down the front, typically worn over a shirt, with pockets and a collar, often made of fabric or denim",
        "ville" : " A cityscape with tall buildings, windows, and street below",
        "voiture" : " A car in profile view, showing wheels, windows, and headlights",
        "volet" : " A window shutter partly closed, showing slats and hinges",
        "xylophone" : " A musical instrument with colorful wooden or metal bars arranged by pitch, often on a stand, with small mallets nearby or in use",
        "mercure" : "A small, cratered gray rocky planet with a barren, heavily pitted surface, similar to the Moon. No atmosphere, stark shadows, and bright sunlight cast sharp contrasts on the terrain. The sky is black, with the Sun appearing larger than on Earth",
        "venus" : "A thickly clouded yellow-orange planet shrouded in dense sulfuric acid clouds. The surface is obscured by haze, with glowing golden light scattering through a toxic atmosphere. Volcanic plains and slow-moving lava flows may be faintly visible beneath the clouds",
        "terre" : "A vivid blue planet with swirling white clouds, deep oceans, and green-brown landmasses. The atmosphere glows with a faint blue halo. From space, the continents and weather systems are clearly visible against the blackness of space",
        "mars" : "A dusty red-orange desert planet with vast canyons, impact craters, and ancient dried riverbeds. The sky has a pink hue due to iron oxide dust, and its two small moons appear faintly. Polar ice caps glisten at the poles",
        "jupiter" : "A massive gas giant with swirling bands of white, beige, orange, and red clouds. The Great Red Spot, a giant storm, is visible as a swirling oval. The planet has a dramatic sense of motion and scale, often accompanied by its four largest moons in orbit",
        "saturne" : "A pale yellow gas giant with a stunning, wide, and complex ring system made of ice and rock. The rings cast shadows on the planet’s surface. The atmosphere features soft bands and subtle storms in pastel tones",
        "neptune" : "A deep blue gas giant with faint atmospheric bands and dynamic white storm systems. The planet appears serene and icy, with a subtle bluish glow. Triton, its largest moon, may be seen nearby, appearing cold and gray",
        "uranus" : "A pale cyan or turquoise gas giant with a smooth, almost featureless atmosphere. Faint rings encircle it vertically due to its extreme axial tilt. The lighting is soft and cold, giving it an ethereal appearance",
        "pluton" : "A small, distant dwarf planet with a reddish-brown, icy surface marked by dark patches and a bright, heart-shaped region. The surrounding space is dark, with Charon, its largest moon, visible nearby. The lighting is dim and remote",
        "galaxie" : "A sprawling, luminous structure composed of billions of stars, often shown as a spiral or elliptical shape. Swirling arms filled with glowing gas clouds, star clusters, and dark dust lanes extend from a bright galactic core. Surrounded by countless stars in deep space",
        "nebuleuse" : "A colorful, cloud-like formation of interstellar gas and dust, glowing in hues of blue, pink, purple, or green. The shapes are irregular and ethereal, with wisps, tendrils, and bright stars forming within the clouds. Often semi-transparent and illuminated by nearby starlight",
        "melon" : "A round or oval fruit with a thick, netted rind that can be beige or greenish, and a juicy, sweet interior that ranges from orange to pale green. Often shown sliced open to reveal the seeds in the center and the smooth, moist flesh",
        "citron" : "A bright yellow, oval-shaped citrus fruit with a textured, shiny skin. The interior is segmented, juicy, and slightly translucent, often depicted sliced to reveal its radiating sections and small white seeds",
        "kiwi" : "A small, oval fruit with a fuzzy brown skin and vibrant green flesh inside, dotted with a ring of tiny black seeds around a pale center. Often shown cut in half to highlight its vivid, symmetrical interior",
        "poire" : "A bulbous fruit with a narrow top and wider base, smooth skin that ranges from green to yellow or red, and a soft, grainy interior. Often shown with a slight shine and a long stem, sometimes sliced to reveal its pale core and small seeds",
        "pêche" : "A round, slightly fuzzy-skinned fruit in shades of orange and red. The inside is soft and juicy with a central pit. Often depicted halved to expose the reddish stone and vibrant yellow-orange flesh",
        "orange" : "A round, thick-skinned citrus fruit with a bright orange color. The peel is slightly bumpy, and the interior is divided into juicy segments. Often shown peeled or sliced to display the fibrous, glossy flesh inside",
        "courgette" : "A long, cylindrical vegetable with smooth, dark green skin and pale, firm flesh inside. Often depicted whole or sliced into discs, showing the soft seeds and subtle texture within",
        "maïs" : "A cylindrical ear of golden-yellow kernels tightly packed on a cob, partially or fully wrapped in green husks with silk strands at the top. Often shown grilled or raw, with plump, shiny kernels",
        "clémentine" : "A small, round citrus fruit with a smooth, bright orange skin that is easy to peel. The interior is sweet, seedless, and segmented. Often shown peeled or with the skin partly removed to expose the shiny flesh",
        "jambon" : "Thinly sliced or thick-cut cured pork meat, pinkish with white fat marbling or borders. Often depicted rolled, folded, or laid flat, with a moist texture and subtle sheen from curing"
    }

    # Générer les prompts personnalisés
    custom_prompts = []
    for mot in mots:
        desc = descriptions.get(mot, f"a symbolic representation of the word '{mot}'")
        prompt = (
            f'A hand-drawn illustration on white textured paper. '
            f'At the top, the word "{mot}" is written in lowercase bold black letters. '
            f'Below the word, a detailed ink-style drawing shows {desc}. '
            f'The drawing features cross-hatching shadows color and a sketchy, ink-pen rendering with color in square form paper. '
            f'The illustration is centered and clear. The background has the texture of slightly aged, white paper, '
            f'enhancing the traditional drawing effect. The overall style is reminiscent of naturalist or dictionary illustrations.'
        )
        custom_prompts.append((mot, prompt))

    # Écriture dans le fichier
    with open('travail.txt', 'w', encoding='utf-8') as kFile:
        for kprompt in custom_prompts:
            kFile.write(str(kprompt[0])+':\n')
            kFile.write(str(kprompt[1])+'\n\n')


if __name__ == "__main__":
    main()
    print("Fin du programme.")
    input("Appuyez sur Entrée pour quitter...")